In [2]:
import json
import pandas as pd

## Leitura dos dados normalizados

In [12]:
props_sf = pd.read_json('../data/senado/proposicoes_normalizadas.json', encoding='utf-8')
props_cd = pd.read_json('../data/camara/proposicoes_normalizadas.json', encoding='utf-8')

In [13]:
props_sf[props_sf.outros_nomes.apply(lambda x: isinstance(x, list) and len(x) != 0)]

,id,uri,ano,nome,nome_inicial,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,outros_nomes,transformado_em_norma,norma_gerada,sigla_tipo,tipo
0,2532267,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 2016/2000,MPV 2016/2000,2016,"Abre ao Orçamento Fiscal da União, em favor do...",2000-01-05T00:00:00,"[CREDITO EXTRAORDINARIO, ORÇAMENTO FISCAL, UNI...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,"[{'nome': 'MSG 28/2000', 'casa': 'CN'}, {'nome...",False,None,MPV,Medida Provisória
1,2532210,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1935-10/2000,MPV 1935-10/2000,1935,Autoriza o Poder Executivo a abrir aos Orçamen...,2000-01-07T00:00:00,"[CREDITO EXTRAORDINARIO, ORÇAMENTO DA SEGURIDA...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,"[{'nome': 'MSG 32/2000', 'casa': 'CN'}, {'nome...",False,None,MPV,Medida Provisória
2,2531545,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1969-12/2000,MPV 1969-12/2000,1969,"Estabelece critérios para a consolidação, a as...",2000-01-07T00:00:00,"[FIXAÇÃO, CRITERIOS, CONSOLIDAÇÃO, REFINANCIAM...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,"[{'nome': 'MSG 66/2000', 'casa': 'CN'}, {'nome...",False,None,MPV,Medida Provisória
3,2532001,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1947-22/2000,MPV 1947-22/2000,1947,Dispõe sobre o salário mínimo a vigorar a part...,2000-01-07T00:00:00,"[FIXAÇÃO, VALOR, REAJUSTE, AUMENTO, SALARIO MI...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,"[{'nome': 'MSG 44/2000', 'casa': 'CN'}, {'nome...",False,None,MPV,Medida Provisória
4,2532191,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1936-42/2000,MPV 1936-42/2000,1936,"Altera a redação dos arts. 14, 18, 34, 44 e 49...",2000-01-07T00:00:00,"[PROIBIÇÃO, INCLUSÃO, LEI DE DIRETRIZES ORÇAME...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,"[{'nome': 'MSG 33/2000', 'casa': 'CN'}, {'nome...",False,None,MPV,Medida Provisória
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39797,8611954,https://legis.senado.leg.br/dadosabertos/proce...,2023,PEC 72/2023,PEC 72/2023,72,Altera o art. 155 da Constituição Federal para...,2023-12-22T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, CONCESSÃO, I...","[{'nome': 'Cleitinho', 'tipo': 'SENADOR', 'uf'...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,SF,"[{'nome': 'PEC 72/2023', 'casa': 'CD'}]",True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
39812,8664217,https://legis.senado.leg.br/dadosabertos/proce...,2024,PEC 18/2024,PEC 18/2024,18,Dá nova redação ao § 4º do art. 225 da Constit...,2024-05-15T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, PATRIMONIO, ...","[{'nome': 'Tereza Cristina', 'tipo': 'SENADOR'...",REMETIDA À CÂMARA DOS DEPUTADOS,False,SF,SF,"[{'nome': 'PEC 18/2024', 'casa': 'CD'}]",False,None,PEC,Proposta de Emenda à Constituição
39817,8699674,https://legis.senado.leg.br/dadosabertos/proce...,2023,PEC 9/2023,PEC 9/2023,9,Impõe aos partidos políticos a obrigatoriedade...,2024-07-12T00:00:00,"[ALTERAÇÃO, REFORÇO, CONSTITUIÇÃO FEDERAL, OBR...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,"[{'nome': 'PEC 9/2023', 'casa': 'CD'}]",True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
39818,8700241,https://legis.senado.leg.br/dadosabertos/proce...,2023,PEC 44/2023,PEC 44/2023,44,Altera o art. 166 da Constituição Federal e ac...,2024-07-16T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSIÇÕES ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",AGUARDANDO DESPACHO,True,SF,CD,"[{'nome': 'PEC 44/2023', 'casa': 'CD'}]",False,None,PEC,Proposta de Emenda à Constituição
39836,8780966,https://legis.senado.leg.br/dadosabertos/proce...,2024,PEC 54/2024,PEC 31/2007,54,"Altera os arts. 37, 163, 165, 212, 212-A e 239...",2024-12-19T00:00:00,"[CRITERIOS, CUSTEIO, DESPESA PUBLICA, EDUCAÇÃO...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,"[{'nome': 'PEC 31/2007', 'casa': 'CD'}]",True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição

In [4]:
props_sf.head()

,id,uri,ano,nome,nome_inicial,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,outros_nomes,transformado_em_norma,norma_gerada,sigla_tipo,tipo
0,2532267,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 2016/2000,MPV 2016/2000,2016,"Abre ao Orçamento Fiscal da União, em favor do...",2000-01-05T00:00:00,"[CREDITO EXTRAORDINARIO, ORÇAMENTO FISCAL, UNI...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,[],False,None,MPV,Medida Provisória
1,2532210,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1935-10/2000,MPV 1935-10/2000,1935,Autoriza o Poder Executivo a abrir aos Orçamen...,2000-01-07T00:00:00,"[CREDITO EXTRAORDINARIO, ORÇAMENTO DA SEGURIDA...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,[],False,None,MPV,Medida Provisória
2,2531545,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1969-12/2000,MPV 1969-12/2000,1969,"Estabelece critérios para a consolidação, a as...",2000-01-07T00:00:00,"[FIXAÇÃO, CRITERIOS, CONSOLIDAÇÃO, REFINANCIAM...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,[],False,None,MPV,Medida Provisória
3,2532001,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1947-22/2000,MPV 1947-22/2000,1947,Dispõe sobre o salário mínimo a vigorar a part...,2000-01-07T00:00:00,"[FIXAÇÃO, VALOR, REAJUSTE, AUMENTO, SALARIO MI...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,[],False,None,MPV,Medida Provisória
4,2532191,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1936-42/2000,MPV 1936-42/2000,1936,"Altera a redação dos arts. 14, 18, 34, 44 e 49...",2000-01-07T00:00:00,"[PROIBIÇÃO, INCLUSÃO, LEI DE DIRETRIZES ORÇAME...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,[],False,None,MPV,Medida Provisória

In [5]:
props_cd.head()

,id,uri,ano,nome,nome_inicial,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
0,13756,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PDC 388/2000,,388,Convoca plebiscito para o eleitorado dos estad...,2000-01-13 00:00:00,"[CONVOCAÇÃO, PLEBISCITO, OPINIÃO PUBLICA, PRIV...","[{'nome': 'Sérgio Novais', 'tipo': 'Deputado(a...",Arquivada,False,CD,CD,False,None,PDC,Projeto de Decreto Legislativo
1,13757,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PDC 389/2000,,389,Aprova o texto do Acordo Multilateral de Segur...,2000-01-12 00:00:00,"[APROVAÇÃO, TEXTO, ATO INTERNACIONAL, ACORDO I...",[{'nome': 'Comissão de Relações Exteriores e d...,Transformado em Norma Jurídica,False,CD,CD,True,"{'nome': 'Decreto Legislativo nº 451/2001', 'a...",PDC,Projeto de Decreto Legislativo
2,13758,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PDC 391/2000,,391,Aprova o texto do Quinto Protocolo ao Acordo G...,2000-01-12 00:00:00,"[APROVAÇÃO, TEXTO, ATO INTERNACIONAL, PROTOCOL...",[{'nome': 'Comissão de Relações Exteriores e d...,Transformado em Norma Jurídica,False,CD,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PDC,Projeto de Decreto Legislativo
3,13759,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PDC 392/2000,,392,Aprova o texto do Acordo de Cooperação Cultura...,2000-01-12 00:00:00,"[APROVAÇÃO, TEXTO, ATO INTERNACIONAL, ACORDO I...",[{'nome': 'Comissão de Relações Exteriores e d...,Transformado em Norma Jurídica,False,CD,CD,True,"{'nome': 'Decreto Legislativo nº 178/2001', 'a...",PDC,Projeto de Decreto Legislativo
4,13760,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PDC 393/2000,PDS 32/2000,393,Aprova a Programação Monetária relativa ao pri...,2000-01-18 00:00:00,"[APROVAÇÃO, PROGRAMAÇÃO FINANCEIRA, RESERVA MO...",[{'nome': 'Senado Federal - Comissão de Assunt...,Arquivada,False,CD,CD,False,None,PDC,Projeto de Decreto Legislativo

In [14]:
sigla_para_tipo_sf = dict(props_sf[['sigla_tipo', 'tipo']].drop_duplicates().sort_values('sigla_tipo').values)
sigla_para_tipo_cd = dict(props_cd[['sigla_tipo', 'tipo']].drop_duplicates().sort_values('sigla_tipo').values)

In [15]:
sigla_para_tipo_sf

{'MPV': 'Medida Provisória',
 'PDL': 'Projeto de Decreto Legislativo',
 'PDN': 'Projeto de Decreto Legislativo (CN)',
 'PDR': 'Projeto de Decreto Legislativo (CR - CN)',
 'PDS': 'Projeto de Decreto Legislativo (SF)',
 'PEC': 'Proposta de Emenda à Constituição',
 'PL': 'Projeto de Lei',
 'PLC': 'Projeto de Lei da Câmara',
 'PLN': 'Projeto de Lei do Congresso Nacional',
 'PLP': 'Projeto de Lei Complementar',
 'PLS': 'Projeto de Lei do Senado',
 'PLV': 'Projeto de Lei de Conversão (CN)',
 'PRN': 'Projeto de Resolução do Congresso Nacional',
 'PRS': 'Projeto de Resolução do Senado'}

In [16]:
sigla_para_tipo_cd

{'MPV': 'Medida Provisória',
 'PDC': 'Projeto de Decreto Legislativo de Sustação de Atos Normativos do Poder Executivo',
 'PDL': 'Projeto de Decreto Legislativo de Alteração de Decreto Legislativo',
 'PDN': 'Projeto de Decreto Legislativo (CN)',
 'PDS': 'Projeto de Decreto Legislativo (SF)',
 'PEC': 'Proposta de Emenda à Constituição',
 'PL': 'Projeto de Lei',
 'PLC': 'Projeto de Lei da Câmara dos Deputados (SF)',
 'PLN': 'Projeto de Lei (CN) de Lei de Diretrizes Orçamentárias (LDO)',
 'PLP': 'Projeto de Lei Complementar',
 'PLS': 'Projeto de Lei do Senado Federal',
 'PLV': 'Projeto de Lei de Conversão',
 'PRC': 'Projeto de Resolução de Alteração do Regimento e outros',
 'PRF': 'Projeto de Resolução do Senado Federal',
 'PRN': 'Projeto de Resolução do Congresso Nacional'}

## Resoluções

### SF

In [17]:
resolucoes_sf = props_sf[props_sf.sigla_tipo.isin([ "PRS"])].copy().reset_index(drop=True)
resolucoes_sf.head()

,id,uri,ano,nome,nome_inicial,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,outros_nomes,transformado_em_norma,norma_gerada,sigla_tipo,tipo
0,3032214,https://legis.senado.leg.br/dadosabertos/proce...,2000,PRS 1/2000,NaN,1,Autoriza a União a contratar operação de reesc...,2000-01-14T00:00:00,"[AUTORIZAÇÃO, SENADO, OPERAÇÃO FINANCEIRA, REE...","[{'nome': 'Comissão de Assuntos Econômicos', '...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,NaN,[],True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PRS,Projeto de Resolução do Senado
1,3032176,https://legis.senado.leg.br/dadosabertos/proce...,2000,PRS 3/2000,NaN,3,Autoriza a República Federativa do Brasil a co...,2000-01-18T00:00:00,"[AUTORIZAÇÃO, SENADO, UNIÃO FEDERAL, EMPRÉSTIM...","[{'nome': 'Comissão de Assuntos Econômicos', '...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,NaN,[],True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PRS,Projeto de Resolução do Senado
2,3032195,https://legis.senado.leg.br/dadosabertos/proce...,2000,PRS 2/2000,NaN,2,Autoria a República Federativa do Brasil a pre...,2000-01-18T00:00:00,"[AUTORIZAÇÃO, SENADO, OPERAÇÃO FINANCEIRA, EMP...","[{'nome': 'Comissão de Assuntos Econômicos', '...",ARQUIVADA,False,SF,NaN,[],True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PRS,Projeto de Resolução do Senado
3,3032157,https://legis.senado.leg.br/dadosabertos/proce...,2000,PRS 4/2000,NaN,4,Autoriza a União a contratar operação de crédi...,2000-01-18T00:00:00,"[AUTORIZAÇÃO, SENADO, EXECUTIVO, OPERAÇÃO FINA...","[{'nome': 'Comissão de Assuntos Econômicos', '...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,NaN,[],True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PRS,Projeto de Resolução do Senado
4,3032138,https://legis.senado.leg.br/dadosabertos/proce...,2000,PRS 5/2000,NaN,5,Autoriza a União a contratar operação de crédi...,2000-01-25T00:00:00,"[AUTORIZAÇÃO, SENADO, EXECUTIVO, OPERAÇÃO FINA...","[{'nome': 'Comissão de Assuntos Econômicos', '...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,NaN,[],True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PRS,Projeto de Resolução do Senado

## PEC

In [57]:
set(props_sf[props_sf.sigla_tipo == 'PEC'].nome).intersection(props_cd[props_cd.sigla_tipo == 'PEC'].nome)

{'PEC 1/2003',
 'PEC 1/2007',
 'PEC 1/2011',
 'PEC 1/2015',
 'PEC 1/2021',
 'PEC 1/2022',
 'PEC 10/2003',
 'PEC 10/2007',
 'PEC 10/2011',
 'PEC 10/2015',
 'PEC 10/2020',
 'PEC 10/2021',
 'PEC 100/2007',
 'PEC 100/2011',
 'PEC 100/2015',
 'PEC 101/2007',
 'PEC 101/2011',
 'PEC 101/2015',
 'PEC 102/2007',
 'PEC 102/2011',
 'PEC 102/2015',
 'PEC 103/2007',
 'PEC 103/2011',
 'PEC 103/2015',
 'PEC 104/2007',
 'PEC 104/2011',
 'PEC 104/2015',
 'PEC 105/2011',
 'PEC 105/2015',
 'PEC 106/2011',
 'PEC 106/2015',
 'PEC 107/2011',
 'PEC 107/2015',
 'PEC 108/2011',
 'PEC 108/2015',
 'PEC 109/2011',
 'PEC 109/2015',
 'PEC 11/2003',
 'PEC 11/2007',
 'PEC 11/2011',
 'PEC 11/2015',
 'PEC 11/2022',
 'PEC 110/2011',
 'PEC 110/2015',
 'PEC 111/2011',
 'PEC 111/2015',
 'PEC 112/2011',
 'PEC 112/2015',
 'PEC 113/2011',
 'PEC 113/2015',
 'PEC 114/2011',
 'PEC 114/2015',
 'PEC 115/2011',
 'PEC 115/2015',
 'PEC 116/2011',
 'PEC 116/2015',
 'PEC 117/2011',
 'PEC 117/2015',
 'PEC 118/2011',
 'PEC 118/2015',
 'PEC 119/2011',
 'PEC 119/2015',
 'PEC 12/2003',
 'PEC 12/2007',
 'PEC 12/2011',
 'PEC 12/2015',
 'PEC 120/2011',
 'PEC 120/2015',
 'PEC 121/2011',
 'PEC 121/2015',
 'PEC 122/2011',
 'PEC 122/2015',
 'PEC 123/2011',
 'PEC 123/2015',
 'PEC 124/2011',
 'PEC 124/2015',
 'PEC 125/2011',
 'PEC 125/2015',
 'PEC 126/2011',
 'PEC 126/2015',
 'PEC 127/2015',
 'PEC 128/2015',
 'PEC 129/2015',
 'PEC 13/2003',
 'PEC 13/2007',
 'PEC 13/2011',
 'PEC 13/2015',
 'PEC 13/2019',
 'PEC 13/2021',
 'PEC 130/2015',
 'PEC 131/2015',
 'PEC 132/2015',
 'PEC 133/2015',
 'PEC 133/2019',
 'PEC 134/2015',
 'PEC 135/2015',
 'PEC 136/2015',
 'PEC 137/2015',
 'PEC 138/2015',
 'PEC 139/2015',
 'PEC 14/2003',
 'PEC 14/2007',
 'PEC 14/2011',
 'PEC 14/2015',
 'PEC 140/2015',
 'PEC 141/2015',
 'PEC 142/2015',
 'PEC 143/2015',
 'PEC 144/2015',
 'PEC 145/2015',
 'PEC 146/2015',
 'PEC 147/2015',
 'PEC 148/2015',
 'PEC 149/2015',
 'PEC 15/2003',
 'PEC 15/2007',
 'PEC 15/2011',
 'PEC 15/2015',
 'PEC 15/2022',
 'PEC 150/2015',
 'PEC 151/2015',
 'PEC 152/2015',
 'PEC 152/2019',
 'PEC 153/2015',
 'PEC 154/2015',
 'PEC 155/2015',
 'PEC 156/2015',
 'PEC 157/2015',
 'PEC 158/2015',
 'PEC 159/2015',
 'PEC 16/2003',
 'PEC 16/2007',
 'PEC 16/2011',
 'PEC 16/2015',
 'PEC 160/2015',
 'PEC 161/2015',
 'PEC 162/2015',
 'PEC 162/2019',
 'PEC 17/2003',
 'PEC 17/2007',
 'PEC 17/2011',
 'PEC 17/2015',
 'PEC 17/2019',
 'PEC 18/2003',
 'PEC 18/2007',
 'PEC 18/2011',
 'PEC 18/2015',
 'PEC 18/2020',
 'PEC 18/2021',
 'PEC 186/2019',
 'PEC 19/2003',
 'PEC 19/2007',
 'PEC 19/2011',
 'PEC 19/2015',
 'PEC 2/2003',
 'PEC 2/2007',
 'PEC 2/2011',
 'PEC 2/2015',
 'PEC 20/2003',
 'PEC 20/2007',
 'PEC 20/2011',
 'PEC 20/2015',
 'PEC 21/2003',
 'PEC 21/2007',
 'PEC 21/2011',
 'PEC 21/2015',
 'PEC 22/2003',
 'PEC 22/2007',
 'PEC 22/2011',
 'PEC 22/2015',
 'PEC 23/2003',
 'PEC 23/2007',
 'PEC 23/2011',
 'PEC 23/2015',
 'PEC 23/2021',
 'PEC 24/2003',
 'PEC 24/2007',
 'PEC 24/2011',
 'PEC 24/2015',
 'PEC 25/2003',
 'PEC 25/2007',
 'PEC 25/2011',
 'PEC 25/2015',
 'PEC 26/2003',
 'PEC 26/2007',
 'PEC 26/2011',
 'PEC 26/2015',
 'PEC 26/2022',
 'PEC 27/2003',
 'PEC 27/2007',
 'PEC 27/2011',
 'PEC 27/2015',
 'PEC 28/2003',
 'PEC 28/2007',
 'PEC 28/2011',
 'PEC 28/2015',
 'PEC 29/2003',
 'PEC 29/2007',
 'PEC 29/2011',
 'PEC 29/2015',
 'PEC 29/2020',
 'PEC 3/2003',
 'PEC 3/2007',
 'PEC 3/2011',
 'PEC 3/2015',
 'PEC 3/2020',
 'PEC 30/2003',
 'PEC 30/2007',
 'PEC 30/2011',
 'PEC 30/2015',
 'PEC 31/2003',
 'PEC 31/2007',
 'PEC 31/2011',
 'PEC 31/2015',
 'PEC 32/2003',
 'PEC 32/2007',
 'PEC 32/2011',
 'PEC 32/2015',
 'PEC 32/2021',
 'PEC 32/2022',
 'PEC 33/2003',
 'PEC 33/2007',
 'PEC 33/2011',
 'PEC 33/2015',
 'PEC 34/2003',
 'PEC 34/2007',
 'PEC 34/2011',
 'PEC 34/2015',
 'PEC 34/2019',
 'PEC 35/2003',
 'PEC 35/2007',
 'PEC 35/2011',
 'PEC 35/2015',
 'PEC 36/2003',
 'PEC 36/2007',
 'PEC 36/2011',
 'PEC 36/2015',
 'PEC 37/2003',
 'PEC 37/2007',
 'PEC 37/2011',
 'PEC 37/2015',
 'PEC 38/2003',
 'PEC 38/2007',
 'PEC 38/2011',
 'PEC 38/2015',
 'PEC 39/2003',
 'PEC 39/2007',
 'PEC 39/2011',
 'PEC 39/2015',
 'PEC 4/2003',
 'PEC 4/2007',
 'PEC 4/2011',
 'PEC 4/2015',
 'PEC 4/2021',
 'PEC 40/2003',
 'PEC 40/2007',
 'PEC 40/2011',
 'PEC 40/2015',
 'PEC 41/2003',
 'PEC 41/2007',
 'PEC 41/2011',
 'PEC 41/2015',
 'PEC 42/2003',
 'PEC 42/2007',
 'PEC 42/2011',
 'PEC 42/2015',
 'PEC 43/2003',
 'PEC 43/2007',
 'PEC 43/2011',
 'PEC 43/2015',
 'PEC 44/2003',
 'PEC 44/2007',
 'PEC 44/2011',
 'PEC 44/2015',
 'PEC 44/2023',
 'PEC 45/2003',
 'PEC 45/2007',
 'PEC 45/2011',
 'PEC 45/2015',
 'PEC 45/2019',
 'PEC 45/2023',
 'PEC 46/2003',
 'PEC 46/2007',
 'PEC 46/2011',
 'PEC 46/2015',
 'PEC 46/2021',
 'PEC 47/2003',
 'PEC 47/2007',
 'PEC 47/2011',
 'PEC 47/2015',
 'PEC 47/2021',
 'PEC 48/2003',
 'PEC 48/2007',
 'PEC 48/2011',
 'PEC 48/2015',
 'PEC 49/2003',
 'PEC 49/2007',
 'PEC 49/2011',
 'PEC 49/2015',
 'PEC 5/2003',
 'PEC 5/2007',
 'PEC 5/2011',
 'PEC 5/2015',
 'PEC 50/2003',
 'PEC 50/2007',
 'PEC 50/2011',
 'PEC 50/2015',
 'PEC 51/2003',
 'PEC 51/2007',
 'PEC 51/2011',
 'PEC 51/2015',
 'PEC 52/2003',
 'PEC 52/2007',
 'PEC 52/2011',
 'PEC 52/2015',
 'PEC 53/2003',
 'PEC 53/2007',
 'PEC 53/2011',
 'PEC 53/2015',
 'PEC 54/2003',
 'PEC 54/2007',
 'PEC 54/2011',
 'PEC 54/2015',
 'PEC 55/2003',
 'PEC 55/2007',
 'PEC 55/2011',
 'PEC 55/2015',
 'PEC 56/2003',
 'PEC 56/2007',
 'PEC 56/2011',
 'PEC 56/2015',
 'PEC 57/2003',
 'PEC 57/2007',
 'PEC 57/2011',
 'PEC 57/2015',
 'PEC 58/2003',
 'PEC 58/2007',
 'PEC 58/2011',
 'PEC 58/2015',
 'PEC 59/2003',
 'PEC 59/2007',
 'PEC 59/2011',
 'PEC 59/2015',
 'PEC 6/2003',
 'PEC 6/2007',
 'PEC 6/2011',
 'PEC 6/2015',
 'PEC 6/2019',
 'PEC 60/2003',
 'PEC 60/2007',
 'PEC 60/2011',
 'PEC 60/2015',
 'PEC 61/2003',
 'PEC 61/2007',
 'PEC 61/2011',
 'PEC 61/2015',
 'PEC 62/2003',
 'PEC 62/2007',
 'PEC 62/2011',
 'PEC 62/2015',
 'PEC 63/2003',
 'PEC 63/2007',
 'PEC 63/2011',
 'PEC 63/2015',
 'PEC 64/2003',
 'PEC 64/2007',
 'PEC 64/2011',
 'PEC 64/2015',
 'PEC 65/2003',
 'PEC 65/2007',
 'PEC 65/2011',
 'PEC 65/2015',
 'PEC 66/2003',
 'PEC 66/2007',
 'PEC 66/2011',
 'PEC 66/2015',
 'PEC 66/2023',
 'PEC 67/2003',
 'PEC 67/2007',
 'PEC 67/2011',
 'PEC 67/2015',
 'PEC 68/2003',
 'PEC 68/2007',
 'PEC 68/2011',
 'PEC 68/2015',
 'PEC 69/2003',
 'PEC 69/2007',
 'PEC 69/2011',
 'PEC 69/2015',
 'PEC 69/2019',
 'PEC 7/2003',
 'PEC 7/2007',
 'PEC 7/2011',
 'PEC 70/2003',
 'PEC 70/2007',
 'PEC 70/2011',
 'PEC 70/2015',
 'PEC 71/2003',
 'PEC 71/2007',
 'PEC 71/2011',
 'PEC 71/2015',
 'PEC 72/2003',
 'PEC 72/2007',
 'PEC 72/2011',
 'PEC 72/2015',
 'PEC 72/2023',
 'PEC 73/2003',
 'PEC 73/2007',
 'PEC 73/2011',
 'PEC 73/2015',
 'PEC 74/2003',
 'PEC 74/2007',
 'PEC 74/2011',
 'PEC 74/2015',
 'PEC 75/2003',
 'PEC 75/2007',
 'PEC 75/2011',
 'PEC 75/2015',
 'PEC 75/2019',
 'PEC 76/2003',
 'PEC 76/2007',
 'PEC 76/2011',
 'PEC 76/2015',
 'PEC 77/2003',
 'PEC 77/2007',
 'PEC 77/2011',
 'PEC 77/2015',
 'PEC 78/2003',
 'PEC 78/2007',
 'PEC 78/2011',
 'PEC 78/2015',
 'PEC 79/2003',
 'PEC 79/2007',
 'PEC 79/2011',
 'PEC 79/2015',
 'PEC 8/2003',
 'PEC 8/2007',
 'PEC 8/2011',
 'PEC 8/2015',
 'PEC 8/2021',
 'PEC 80/2003',
 'PEC 80/2007',
 'PEC 80/2011',
 'PEC 80/2015',
 'PEC 81/2003',
 'PEC 81/2007',
 'PEC 81/2011',
 'PEC 81/2015',
 'PEC 82/2003',
 'PEC 82/2007',
 'PEC 82/2011',
 'PEC 82/2015',
 'PEC 83/2003',
 'PEC 83/2007',
 'PEC 83/2011',
 'PEC 83/2015',
 'PEC 84/2003',
 'PEC 84/2007',
 'PEC 84/2011',
 'PEC 84/2015',
 'PEC 85/2003',
 'PEC 85/2007',
 'PEC 85/2011',
 'PEC 85/2015',
 'PEC 86/2003',
 'PEC 86/2007',
 'PEC 86/2011',
 'PEC 86/2015',
 'PEC 87/2003',
 'PEC 87/2007',
 'PEC 87/2011',
 'PEC 87/2015',
 'PEC 88/2003',
 'PEC 88/2007',
 'PEC 88/2011',
 'PEC 88/2015',
 'PEC 89/2003',
 'PEC 89/2007',
 'PEC 89/2011',
 'PEC 89/2015',
 'PEC 9/2003',
 'PEC 9/2007',
 'PEC 9/2011',
 'PEC 9/2015',
 'PEC 9/2023',
 'PEC 90/2003',
 'PEC 90/2007',
 'PEC 90/2011',
 'PEC 90/2015',
 'PEC 91/2003',
 'PEC 91/2007',
 'PEC 91/2011',
 'PEC 91/2015',
 'PEC 92/2003',
 'PEC 92/2007',
 'PEC 92/2011',
 'PEC 92/2015',
 'PEC 93/2003',
 'PEC 93/2007',
 'PEC 93/2011',
 'PEC 93/2015',
 'PEC 94/2003',
 'PEC 94/2007',
 'PEC 94/2011',
 'PEC 94/2015',
 'PEC 95/2003',
 'PEC 95/2007',
 'PEC 95/2011',
 'PEC 95/2015',
 'PEC 95/2019',
 'PEC 96/2003',
 'PEC 96/2007',
 'PEC 96/2011',
 'PEC 96/2015',
 'PEC 97/2003',
 'PEC 97/2007',
 'PEC 97/2011',
 'PEC 97/2015',
 'PEC 98/2003',
 'PEC 98/2007',
 'PEC 98/2011',
 'PEC 98/2015',
 'PEC 98/2019',
 'PEC 99/2007',
 'PEC 99/2011',
 'PEC 99/2015'}

In [65]:
props_sf[props_sf.nome == 'PEC 23/2007']

,id,uri,ano,nome,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
38642,3049405,https://legis.senado.leg.br/dadosabertos/proce...,2007,PEC 23/2007,23,Altera os artigos 17 e 55 da Constituição Fede...,2007-03-21T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, PARTIDO POLI...","[{'nome': 'Marco Maciel', 'tipo': 'SENADOR', '...",REMETIDA À CÂMARA DOS DEPUTADOS,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição

In [66]:
props_cd[props_cd.nome == 'PEC 23/2007']

,id,uri,ano,nome,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
21777,345331,https://dadosabertos.camara.leg.br/api/v2/prop...,2007,PEC 23/2007,23,Altera o Art. 159 da Constituição Federal e ac...,2007-03-20 17:02:00,"[Constituição Federal (1988), Ato das Disposiç...","[{'nome': 'Abelardo Camarinha', 'tipo': 'Deput...",Arquivada,False,CD,CD,False,None,PEC,Proposta de Emenda à Constituição

In [64]:
props_sf[(props_sf.sigla_tipo == 'PEC') & props_sf.norma_gerada].head(30)

,id,uri,ano,nome,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
38193,2530869,https://legis.senado.leg.br/dadosabertos/proce...,2000,PEC 4/2000,4,Acrescenta o art. 76 ao Ato das Disposições Co...,2000-01-27T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSIÇÕES ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38219,2530150,https://legis.senado.leg.br/dadosabertos/proce...,2000,PEC 29/2000,29,Introduz modificações na estrutura do Poder Ju...,2000-06-30T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, JUDICIÁRIO. ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",INFORMAÇÕES RECEBIDAS,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38257,1421948,https://legis.senado.leg.br/dadosabertos/proce...,2001,PEC 21/2001,21,Altera a redação do artigo 6º da Constituição ...,2001-08-07T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, INCLUSÃO, DI...","[{'nome': 'Antonio Carlos Valadares', 'tipo': ...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38265,1421792,https://legis.senado.leg.br/dadosabertos/proce...,2001,PEC 29/2001,29,Cria os Tribunais Regionais Federais da 6º e 7...,2001-08-24T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, FIXAÇÃO, NOR...","[{'nome': 'Arlindo Porto', 'tipo': 'SENADOR', ...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38272,1421649,https://legis.senado.leg.br/dadosabertos/proce...,2001,PEC 36/2001,36,"Dá nova redação à alínea ""c"" do inciso XVI do ...",2001-09-27T00:00:00,"[ALTERAÇÃO, DISPOSITIVOS, ATO, DISPOSIÇÕES CON...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38278,2526276,https://legis.senado.leg.br/dadosabertos/proce...,2001,PEC 42/2001,42,"Altera os artigos 149, 155 e 177 da Constituiç...",2001-10-15T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, SISTEMA TRIB...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38296,1421170,https://legis.senado.leg.br/dadosabertos/proce...,2002,PEC 3/2002,3,Acrescenta o art. 149-A à Constituição Federal...,2002-02-27T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, SISTEMA TRIB...","[{'nome': 'Alvaro Dias', 'tipo': 'SENADOR', 'u...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38297,2525766,https://legis.senado.leg.br/dadosabertos/proce...,2002,PEC 5/2002,5,Dá nova redação ao parágrafo 1º do artigo 222 ...,2002-02-27T00:00:00,"[ALTERAÇÃO, DISPOSITIVOS, COMUNICAÇÃO SOCIAL, ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38298,1421148,https://legis.senado.leg.br/dadosabertos/proce...,2002,PEC 4/2002,4,Dá nova redação ao parágrafo 1º do artigo 17 d...,2002-02-27T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSITIVOS...","[{'nome': 'Bernardo Cabral', 'tipo': 'SENADOR'...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38311,3054204,https://legis.senado.leg.br/dadosabertos/proce...,2002,PEC 18/2002,18,Altera os artigos 100 e 156 da Constituição Fe...,2002-04-29T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSIÇÕES ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38312,2525692,https://legis.senado.leg.br/dadosabertos/proce...,2002,PEC 19/2002,19,Acrescenta o artigo 84 ao Ato das Disposições ...,2002-04-30T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSIÇÕES ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38335,1420488,https://legis.senado.leg.br/dadosabertos/proce...,2003,PEC 7/2003,7,Altera a redação da alínea b e acrescenta alín...,2003-03-26T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSITIVOS...","[{'nome': 'Jorge Bornhausen', 'tipo': 'SENADOR...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38370,1419828,https://legis.senado.leg.br/dadosabertos/proce...,2003,PEC 42/2003,42,"Altera o art. 40 da Constituição Federal, rela...",2003-06-02T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, ADMINISTRAÇÃ...","[{'nome': 'Pedro Simon', 'tipo': 'SENADOR', 'u...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38385,1419575,https://legis.senado.leg.br/dadosabertos/proce...,2003,PEC 57/2003,57,Acrescenta o § 3º ao artigo 215 da Constituiçã...,2003-08-05T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, EXIGÊNCIA, L...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38395,2523965,https://legis.senado.leg.br/dadosabertos/proce...,2003,PEC 67/2003,67,"Modifica os artigos 37, 40, 42, 48, 96, 1...",2003-08-28T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, ADMINISTRAÇÃ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38402,2523872,https://legis.senado.leg.br/dadosabertos/proce...,2003,PEC 74/2003,74,Altera o Sistema Tributário Nacional e dá outr...,2003-09-25T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, SISTEMA TRIB...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38415,3053524,https://legis.senado.leg.br/dadosabertos/proce...,2003,PEC 87/2003,87,Altera o artigo 89 do Ato das Disposições Cons...,2003-11-13T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSIÇÕES ...","[{'nome': 'Fátima Cleide', 'tipo': 'SENADOR', ...",REMETIDA À CÂMARA DOS DEPUTADOS,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38424,3053317,https://legis.senado.leg.br/dadosabertos/proce...,2003,PEC 96/2003,96,Acrescenta novo parágrafo ao artigo 73 do Ato ...,2003-12-09T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, ACRÉSCIMO, D...","[{'nome': 'Ideli Salvatti', 'tipo': 'SENADOR',...",REMETIDA À CÂMARA DOS DEPUTADOS,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38440,3047036,https://legis.senado.leg.br/dadosabertos/proce...,2004,PEC 12A/2004,12A,Acrescenta artigo ao Ato das Disposições Const...,2004-03-17T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSIÇÕES ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38443,1418877,https://legis.senado.leg.br/dadosabertos/proce...,2004,PEC 15/2004,15,Altera o inciso IV do art. 20 da Constituição ...,2004-03-31T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, EXCLUSÃO, DO...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38445,2523439,https://legis.senado.leg.br/dadosabertos/proce...,2004,PEC 17/2004,17,Altera o Sistema Tributário Nacional e dá outr...,2004-04-07T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, SISTEMA TRIB...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38498,3051597,https://legis.senado.leg.br/dadosabertos/proce...,2003,PEC 77A/2003,77A,"Altera os artigos 28, 37, 40, 195 e 201 da Con...",2005-03-22T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, ADMINISTRAÇÃ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",ARQUIVADA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38573,1416686,https://legis.senado.leg.br/dadosabertos/proce...,2006,PEC 8/2006,8,Modifica o art. 57 da Constituição Federal. (D...,2006-02-02T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, LEGISLATIVO,...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",ARQUIVADA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38574,1416722,https://legis.senado.leg.br/dadosabertos/proce...,2006,PEC 7/2006,7,"Acrescenta os §§ 4º, 5º e 6º ao art. 198 da Co...",2006-02-02T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, ADMINISTRAÇÃ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38575,1416650,https://legis.senado.leg.br/dadosabertos/proce...,2006,PEC 9/2006,9,"Dá nova redação aos arts. 23, 30, 206 e 212 da...",2006-02-07T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, (ADCT), INCL...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38579,3046123,https://legis.senado.leg.br/dadosabertos/proce...,2006,PEC 12A/2006,12A,Altera o art. 100 da Constituição Federal e ac...,2006-03-07T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, ACRÉSCIMO, D...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38589,1416423,https://legis.senado.leg.br/dadosabertos/proce...,2006,PEC 22/2006,22,"Altera o art. 103-B, para modificar a composiç...",2006-05-10T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, PODER JUDICI...","[{'nome': 'Demóstenes Torres', 'tipo': 'SENADO...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38642,3049405,https://legis.senado.leg.br/dadosabertos/proce...,2007,PEC 23/2007,23,Altera os artigos 17 e 55 da Constituição Fede...,2007-03-21T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, PARTIDO POLI...","[{'nome': 'Marco Maciel', 'tipo': 'SENADOR', '...",REMETIDA À CÂMARA DOS DEPUTADOS,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38694,2521446,https://legis.senado.leg.br/dadosabertos/proce...,2007,PEC 75/2007,75,"Altera o art. 159 da Constituição Federal, aum...",2007-08-20T00:00:00,"[Alteração, Constituição Federal, Sistema Trib...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38708,2521258,https://legis.senado.leg.br/dadosabertos/proce...,2007,PEC 89/2007,89,Prorroga os prazos previstos no caput dos arts...,2007-10-10T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSIÇÕES ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição

In [42]:
props_sf[props_sf.sigla_tipo == 'PEC']

,id,uri,ano,nome,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
38190,1423348,https://legis.senado.leg.br/dadosabertos/proce...,2000,PEC 1/2000,1,Altera o artigo 104 da Constituição Federal e ...,2000-01-18T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, INCLUSÃO, LI...","[{'nome': 'Tião Viana', 'tipo': 'SENADOR', 'uf...",ARQUIVADA AO FINAL DA LEGISLATURA,False,SF,SF,False,None,PEC,Proposta de Emenda à Constituição
38191,1423326,https://legis.senado.leg.br/dadosabertos/proce...,2000,PEC 2/2000,2,Insere dispositivo na Constituição Federal par...,2000-01-19T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, INCLUSÃO, NO...","[{'nome': 'José Alencar', 'tipo': 'SENADOR', '...",ARQUIVADA AO FINAL DA LEGISLATURA,False,SF,SF,False,None,PEC,Proposta de Emenda à Constituição
38192,1423304,https://legis.senado.leg.br/dadosabertos/proce...,2000,PEC 3/2000,3,"Altera o caput e os § 4º, 6º, II e 7º e acresc...",2000-01-20T00:00:00,"[ALTERAÇÃO, DISPOSITIVOS, LEGISLATIVO, REUNIÃO...","[{'nome': 'Jader Barbalho', 'tipo': 'SENADOR',...",ARQUIVADA,False,SF,SF,False,None,PEC,Proposta de Emenda à Constituição
38193,2530869,https://legis.senado.leg.br/dadosabertos/proce...,2000,PEC 4/2000,4,Acrescenta o art. 76 ao Ato das Disposições Co...,2000-01-27T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSIÇÕES ...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição
38194,1423282,https://legis.senado.leg.br/dadosabertos/proce...,2000,PEC 5/2000,5,Dispõe sobre o recesso parlamentar e as férias...,2000-02-01T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSITIVOS...","[{'nome': 'José Roberto Arruda', 'tipo': 'SENA...",PREJUDICADA,False,SF,SF,False,None,PEC,Proposta de Emenda à Constituição
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39832,8771508,https://legis.senado.leg.br/dadosabertos/proce...,2024,PEC 49/2024,49,"Altera a Emenda Constitucional nº 132, de 20 d...",2024-12-11T00:00:00,"[ALTERAÇÃO, EMENDA CONSTITUCIONAL, CONSTITUIÇÃ...","[{'nome': 'Eduardo Gomes', 'tipo': 'SENADOR', ...",MATÉRIA COM A RELATORIA,True,SF,SF,False,None,PEC,Proposta de Emenda à Constituição
39833,8772231,https://legis.senado.leg.br/dadosabertos/proce...,2024,PEC 50/2024,50,"Acrescenta ao art. 73, da Constituição Federal...",2024-12-12T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, ACRESCIMO, C...","[{'nome': 'Cleitinho', 'tipo': 'SENADOR', 'uf'...",AGUARDANDO DESIGNAÇÃO DO RELATOR,True,SF,SF,False,None,PEC,Proposta de Emenda à Constituição
39834,8776422,https://legis.senado.leg.br/dadosabertos/proce...,2024,PEC 52/2024,52,"Modifica o art. 93 da Constituição Federal, pa...",2024-12-17T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, COMPOSIÇÃO, ...","[{'nome': 'Ana Paula Lobato', 'tipo': 'SENADOR...",AGUARDANDO DESIGNAÇÃO DO RELATOR,True,SF,SF,False,None,PEC,Proposta de Emenda à Constituição
39835,8780865,https://legis.senado.leg.br/dadosabertos/proce...,2024,PEC 53/2024,53,Dá nova redação à alínea “d” do inciso XXXVIII...,2024-12-19T00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DIREITOS E G...","[{'nome': 'Flávio Bolsonaro', 'tipo': 'SENADOR...",AGUARDANDO DESIGNAÇÃO DO RELATOR,True,SF,SF,False,None,PEC,Proposta de Emenda à Constituição
39836,8780966,https://legis.senado.leg.br/dadosabertos/proce...,2024,PEC 54/2024,54,"Altera os arts. 37, 163, 165, 212, 212-A e 239...",2024-12-19T00:00:00,"[CRITERIOS, CUSTEIO, DESPESA PUBLICA, EDUCAÇÃO...","[{'nome': 'Câmara dos Deputados', 'tipo': 'CAM...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PEC,Proposta de Emenda à Constituição

In [55]:
props_sf[props_sf.nome == 'PEC 200/2000']

Empty DataFrame
Columns: [id, uri, ano, nome, numero, ementa, data_apresentacao, palavras_chave, autoria, situacao_atual, em_tramitacao, casa_atual, casa_origem, transformado_em_norma, norma_gerada, sigla_tipo, tipo]
Index: []

In [53]:
props_cd[(props_cd.ano == 2000) & (props_cd.sigla_tipo == 'PEC')].numero.min()

np.int64(190)

In [45]:
props_cd[props_cd.sigla_tipo == 'PEC']

,id,uri,ano,nome,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
26,14523,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PEC 190/2000,190,Acrescenta ao Capítulo VIII do Título VIII da ...,2000-01-06 00:00:00,"[Garantia, remanescentes, quilombos, reconheci...","[{'nome': 'Senado Federal - Lúcio Alcântara', ...",Arquivada,False,CD,CD,False,None,PEC,Proposta de Emenda à Constituição
27,14525,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PEC 191/2000,191,Dá nova redação ao inciso XXXIII do art. 7º da...,2000-01-12 00:00:00,"[Alteração, Constituição Federal, Direitos Soc...","[{'nome': 'Alceu Collares', 'tipo': 'Deputado(...",Arquivada,False,CD,CD,False,None,PEC,Proposta de Emenda à Constituição
28,14526,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PEC 192/2000,192,"Dá nova redação aos arts. 31, § 1º, 75, caput,...",2000-01-12 00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, DISPOSIÇÕES ...","[{'nome': 'Wagner Salustiano', 'tipo': 'Deputa...",Arquivada,False,CD,CD,False,None,PEC,Proposta de Emenda à Constituição
29,14527,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PEC 193/2000,193,"Extingue o Tribunal de Contas da União, dos Es...",2000-01-13 00:00:00,"[ALTERAÇÃO, CONSTITUIÇÃO FEDERAL, ORGANIZAÇÃO ...","[{'nome': 'Augusto Franco', 'tipo': 'Deputado(...",Arquivada,False,CD,CD,False,None,PEC,Proposta de Emenda à Constituição
30,14528,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PEC 194/2000,194,Altera o art. 230 do texto constitucional para...,2000-01-26 00:00:00,"[Obrigatoriedade, concessionaria, transporte c...","[{'nome': 'Sérgio Carvalho', 'tipo': 'Deputado...",Arquivada,False,CD,CD,False,None,PEC,Proposta de Emenda à Constituição
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91979,2471383,https://dadosabertos.camara.leg.br/api/v2/prop...,2024,PEC 44/2024,44,Altera o §9º do artigo 166 da Constituição Fed...,2024-11-26 09:57:00,"[Constituição Federal (1988), critério, destin...","[{'nome': 'Acácio Favacho', 'tipo': 'Deputado(...",Aguardando Criação de Comissão Temporária,True,CD,CD,False,None,PEC,Proposta de Emenda à Constituição
92190,2474283,https://dadosabertos.camara.leg.br/api/v2/prop...,2024,PEC 45/2024,45,"Altera os art. 37, art. 163, art. 203, art. 21...",2024-12-03 07:15:00,"[Constituição Federal (1988), contagem, teto c...","[{'nome': 'Poder Executivo', 'tipo': 'Órgão do...",Arquivada,False,CD,CD,False,None,PEC,Proposta de Emenda à Constituição
92597,2478427,https://dadosabertos.camara.leg.br/api/v2/prop...,2024,PEC 48/2024,48,Altera o art. 53 da Constituição Federal para ...,2024-12-11 10:56:00,"[Alteração, Constituição Federal (1988), Imuni...","[{'nome': 'Adilson Barroso', 'tipo': 'Deputado...",Aguardando Despacho do Presidente da Câmara do...,True,CD,CD,False,None,PEC,Proposta de Emenda à Constituição
92679,2479738,https://dadosabertos.camara.leg.br/api/v2/prop...,2024,PEC 51/2024,51,Altera o art. 7º e o Ato das Disposições Const...,2024-12-12 17:45:00,"[Constituição Federal (1988), critério, Condiç...","[{'nome': 'Abilio Brunini', 'tipo': 'Deputado(...",Aguardando Encaminhamento,True,CD,CD,False,None,PEC,Proposta de Emenda à Constituição
92803,2481262,https://dadosabertos.camara.leg.br/api/v2/prop...,2020,PEC 3/2020,3,Altera a Constituição Federal para estabelecer...,2024-12-18 21:29:00,"[Alteração, Constituição Federal (1988), Compe...","[{'nome': 'Senado Federal - Eduardo Gomes', 't...",Aguardando Despacho do Presidente da Câmara do...,True,CD,CD,False,None,PEC,Proposta de Emenda à Constituição

## Resoluções

In [40]:
props_cd.sigla_tipo.value_counts()

sigla_tipo
PL     67107
PDC    11439
PDL     3740
PLP     3404
PEC     2628
PRC     1934
MPV     1286
PLV      683
PLN      559
PRN       55
PLS       20
PDS       10
PLC        6
PDN        2
PRF        1
Name: count, dtype: int64

In [38]:
props_sf.tipo.value_counts()

tipo
Projeto de Decreto Legislativo (SF)           10309
Projeto de Lei do Senado                       9238
Projeto de Lei                                 6192
Medida Provisória                              2888
Projeto de Lei da Câmara                       2883
Projeto de Decreto Legislativo                 1965
Projeto de Resolução do Senado                 1952
Projeto de Lei do Congresso Nacional           1648
Proposta de Emenda à Constituição              1647
Projeto de Lei Complementar                     376
Projeto de Decreto Legislativo (CN)             328
Projeto de Lei de Conversão (CN)                320
Projeto de Resolução do Congresso Nacional       89
Projeto de Decreto Legislativo (CR - CN)          2
Name: count, dtype: int64

In [24]:
props_sf.head(30)

,id,uri,ano,nome,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
0,2532267,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 2016/2000,2016,"Abre ao Orçamento Fiscal da União, em favor do...",2000-01-05T00:00:00,"[CREDITO EXTRAORDINARIO, ORÇAMENTO FISCAL, UNI...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
1,2532210,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1935-10/2000,1935,Autoriza o Poder Executivo a abrir aos Orçamen...,2000-01-07T00:00:00,"[CREDITO EXTRAORDINARIO, ORÇAMENTO DA SEGURIDA...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
2,2531545,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1969-12/2000,1969,"Estabelece critérios para a consolidação, a as...",2000-01-07T00:00:00,"[FIXAÇÃO, CRITERIOS, CONSOLIDAÇÃO, REFINANCIAM...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
3,2532001,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1947-22/2000,1947,Dispõe sobre o salário mínimo a vigorar a part...,2000-01-07T00:00:00,"[FIXAÇÃO, VALOR, REAJUSTE, AUMENTO, SALARIO MI...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
4,2532191,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1936-42/2000,1936,"Altera a redação dos arts. 14, 18, 34, 44 e 49...",2000-01-07T00:00:00,"[PROIBIÇÃO, INCLUSÃO, LEI DE DIRETRIZES ORÇAME...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
5,2532020,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1946-35/2000,1946,Dispõe sobre o salário mínimo para o período d...,2000-01-07T00:00:00,"[NORMAS, REAJUSTE, AUMENTO, SALARIO MINIMO .]","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
6,2531849,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1955-63/2000,1955,Dispõe sobre o pagamento dos militares e dos s...,2000-01-07T00:00:00,"[HIPOTESE, CONCESSÃO, ADIANTAMENTO, PERCENTAGE...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
7,2532172,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1937-11/2000,1937,"Altera dispositivos da Lei nº 9.692, de 27 de ...",2000-01-07T00:00:00,"[ALTERAÇÃO, DISPOSITIVOS, NORMAS, DIRETRIZ, OR...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
8,2532248,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1933-9/2000,1933,Dispõe sobre os reajustes do salário mínimo a ...,2000-01-07T00:00:00,"[NORMAS, REAJUSTE, AUMENTO, SALARIO MINIMO, BE...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
9,2531887,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1953-14/2000,1953,"Institui o Auxílio -Transporte aos militares, ...",2000-01-07T00:00:00,"[FIXAÇÃO, CRITERIOS, CONCESSÃO, AUXILIO-TRANSP...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
10,2531659,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1965-10/2000,1965,Estabelece a nulidade das disposições contratu...,2000-01-07T00:00:00,"[CRITERIOS, DECLARAÇÃO, NULIDADE, CLAUSULA, CO...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
11,2531621,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1967-3/2000,1967,Autoriza o Poder Executivo a abrir ao Orçament...,2000-01-07T00:00:00,"[CREDITO EXTRAORDINARIO, ORÇAMENTO DA SEGURIDA...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
12,2532229,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1934-9/2000,1934,"Altera a Lei nº 4229, de 1º de junho de 1963, ...",2000-01-07T00:00:00,"[ALTERAÇÃO, COMPOSIÇÃO, COMPETENCIA, CONSELHO ...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
13,2531773,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1959-17/2000,1959,"Acresce parágrafo ao art. 4º da Lei nº 9.434, ...",2000-01-07T00:00:00,"[OBRIGATORIEDADE, AUTORIZAÇÃO, FAMILIA, DOAÇÃO...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
14,2532115,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1941-14/2000,1941,Dispõe sobre a aquisição de produtos para a im...,2000-01-07T00:00:00,"[CRITERIOS, MINISTERIO DA SAUDE (MS), AQUISIÇÃ...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
15,2531982,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1948-50/2000,1948,Dispõe sobre a emissão de Notas do Tesouro Nac...,2000-01-07T00:00:00,"[AUTORIZAÇÃO, BANCO DO NORDESTE DO BRASIL S/A ...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
16,2531754,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1960-57/2000,1960,Altera a legislação referente ao Adicional ao ...,2000-01-07T00:00:00,"[ALTERAÇÃO, NORMAS, APLICAÇÃO, RECURSOS FINANC...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
17,2531678,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1964-22/2000,1964,"Altera as Leis nºs 6.368, de 21 de outubro de ...",2000-01-07T00:00:00,"[NORMAS, SISTEMA NACIONAL, COMBATE, DROGA, INT...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
18,2531640,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1966-4/2000,1966,"Altera dispositivos da Lei nº 9365, de 16 de d...",2000-01-07T00:00:00,"[ALTERAÇÃO, DISPOSITIVOS, PERIODO, VIGENCIA, B...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
19,2532039,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1945-47/2000,1945,Dispõe sobre o salário mínimo para o período d...,2000-01-07T00:00:00,"[NORMAS, FIXAÇÃO, VALOR, SALARIO MINIMO .]","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
20,2531906,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1952-19/2000,1952,Altera a Consolidação das Leis do Trabalho - C...,2000-01-07T00:00:00,"[CRITERIOS, PRORROGAÇÃO, COMPENSAÇÃO, JORNADA ...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
21,2531564,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1940-17/2000,1940,"Altera dispositivos do Decreto-Lei nº 73, de 2...",2000-01-07T00:00:00,"[CRITERIOS, SUPERINTENDENCIA DE SEGUROS PRIVAD...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
22,2532096,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1942-13/2000,1942,Dá nova redação a dispositivos da Lei nº 9.491...,2000-01-07T00:00:00,"[ALTERAÇÃO, DISPOSITIVOS, NORMAS, PROGRAMA NAC...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
23,2532134,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1939-24/2000,1939,"Restaura a vigência da Lei nº 8.989, de 24 de ...",2000-01-07T00:00:00,"[EXCLUSÃO, OBRIGATORIEDADE, VEICULO AUTOMOTOR,...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
24,2531925,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1951-21/2000,1951,Dispõe sobre a adoção de medidas relacionadas ...,2000-01-07T00:00:00,"[COMPETENCIA, CONSELHO CURADOR, FUNDO DE GARAN...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
25,2531963,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1949-19/2000,1949,"Acrescenta dispositivo à Lei nº 9.605, de 12 d...",2000-01-07T00:00:00,"[CRITERIOS, AUTORIZAÇÃO, ORGÃOS, SISTEMA NACIO...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
26,2531830,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1956-45/2000,1956,"Dá nova redação aos arts. 3º, 16 e 44 da Lei n...",2000-01-07T00:00:00,"[HIPOTESE, EXCEÇÃO, APLICAÇÃO, NORMAS, PROPRIE...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
27,2531735,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1961-18/2000,1961,Dispõe sobre o Programa de Revitalização de Co...,2000-01-07T00:00:00,"[FIXAÇÃO, CRITERIOS, IMPLEMENTAÇÃO, PROGRAMA D...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
28,2531811,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1957-31/2000,1957,Autoriza a União a receber em valores mobiliár...,2000-01-07T00:00:00,"[AUTORIZAÇÃO, UNIÃO FEDERAL, RECEBIMENTO, DIVI...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória
29,2531944,https://legis.senado.leg.br/dadosabertos/proce...,2000,MPV 1950-59/2000,1950,Dispõe sobre medidas complementares ao Plano R...,2000-01-07T00:00:00,"[CRITERIOS, ADMISSIBILIDADE, PROIBIÇÃO, APLICA...","[{'nome': 'Presidência da República', 'tipo': ...",SEM EFICÁCIA,False,CN,CN,False,None,MPV,Medida Provisória

In [36]:
props_sf[props_sf.nome == 'PLS 338/2017']

,id,uri,ano,nome,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
28739,7197009,https://legis.senado.leg.br/dadosabertos/proce...,2017,PLS 338/2017,338,"Altera a Lei nº 9.250, de 26 de dezembro de 19...",2017-09-20T00:00:00,[],"[{'nome': 'Romário', 'tipo': 'SENADOR', 'uf': ...",REMETIDA À CÂMARA DOS DEPUTADOS,False,SF,SF,False,None,PLS,Projeto de Lei do Senado

In [32]:
props_cd[props_cd.nome == 'PLP 58/2003']

,id,uri,ano,nome,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
10896,119684,https://dadosabertos.camara.leg.br/api/v2/prop...,2003,PLP 58/2003,58,Institui o Cadastro Nacional de Contas no Banc...,2003-06-11 21:11:00,"[Criação, cadastro nacional, contas, Banco Cen...","[{'nome': 'Robson Tuma', 'tipo': 'Deputado(a)'...",NaN,True,CD,CD,False,None,PLP,Projeto de Lei Complementar

In [35]:
props_sf[(props_sf.sigla_tipo == 'PLS') & (props_sf.ano == 2003)]

,id,uri,ano,nome,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
15560,680645,https://legis.senado.leg.br/dadosabertos/proce...,2003,PLS 42/2003,42,Vincula recursos para a seguridade social.,2003-02-26T00:00:00,"[PROJETO DE LEI, SENADO, REGULAMENTAÇÃO, CONST...","[{'nome': 'Paulo Octávio', 'tipo': 'SENADOR', ...",TRAMITAÇÃO ENCERRADA,False,SF,SF,False,None,PLS,Projeto de Lei do Senado
15561,2999031,https://legis.senado.leg.br/dadosabertos/proce...,2003,PLS 68/2003,68,Regulamenta o § 4º do artigo 40 da Constituiçã...,2003-03-18T00:00:00,"[CRIAÇÃO, NORMA JURIDICA, LEI FEDERAL, FIXAÇÃO...","[{'nome': 'Antonio Carlos Valadares', 'tipo': ...",ARQUIVADA AO FINAL DA LEGISLATURA,False,SF,SF,False,None,PLS,Projeto de Lei do Senado
15562,679941,https://legis.senado.leg.br/dadosabertos/proce...,2003,PLS 89/2003,89,Acrescenta § 3º ao artigo 35 da Lei Complement...,2003-03-27T00:00:00,"[ALTERAÇÃO, ACRÉSCIMO, NORMAS, DISPOSITIVOS, C...","[{'nome': 'Hélio Costa', 'tipo': 'SENADOR', 'u...",ARQUIVADA,False,SF,SF,False,None,PLS,Projeto de Lei do Senado
15563,679479,https://legis.senado.leg.br/dadosabertos/proce...,2003,PLS 114/2003,114,"Altera dispositivos da Lei Complementar nº 87,...",2003-04-09T00:00:00,"[ALTERAÇÃO, ACRÉSCIMO, NORMAS, DISPOSITIVOS, C...","[{'nome': 'Romero Jucá', 'tipo': 'SENADOR', 'u...",ARQUIVADA AO FINAL DA LEGISLATURA,False,SF,SF,False,None,PLS,Projeto de Lei do Senado
15564,2998504,https://legis.senado.leg.br/dadosabertos/proce...,2003,PLS 130/2003,130,Acrescenta dispositivos à Lei Complementar nº ...,2003-04-14T00:00:00,"[ALTERAÇÃO, NORMAS, LEI COMPLEMENTAR, DISPOSIT...","[{'nome': 'João Capiberibe', 'tipo': 'SENADOR'...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PLS,Projeto de Lei do Senado
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19107,2994382,https://legis.senado.leg.br/dadosabertos/proce...,2003,PLS 533/2003,533,Dispõe sobre o Sistema de Consórcios.,2003-12-18T00:00:00,"[NORMAS, REGULAMENTO, SISTEMA, CONSÓRCIO, DEFI...","[{'nome': 'Aelton Freitas', 'tipo': 'SENADOR',...",REMETIDA À CÂMARA DOS DEPUTADOS,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PLS,Projeto de Lei do Senado
19108,671277,https://legis.senado.leg.br/dadosabertos/proce...,2003,PLS 536/2003,536,Altera a redação do artigo 2039 da Lei nº 10.4...,2003-12-19T00:00:00,"[ALTERAÇÃO, CÓDIGO CIVIL, PERMISSÃO, CASAMENTO...","[{'nome': 'Demóstenes Torres', 'tipo': 'SENADO...",REMETIDA À CÂMARA DOS DEPUTADOS,False,SF,SF,False,None,PLS,Projeto de Lei do Senado
19109,671255,https://legis.senado.leg.br/dadosabertos/proce...,2003,PLS 537/2003,537,"Altera o artigo 23, e revoga os seus incisos I...",2003-12-19T00:00:00,"[ALTERAÇÃO, LEI FEDERAL, IMPROBIDADE ADMINISTR...","[{'nome': 'Demóstenes Torres', 'tipo': 'SENADO...",REMETIDA À CÂMARA DOS DEPUTADOS,False,SF,SF,False,None,PLS,Projeto de Lei do Senado
19110,671299,https://legis.senado.leg.br/dadosabertos/proce...,2003,PLS 535/2003,535,"Altera a Lei nº 7565, de 19 de dezembro de 198...",2003-12-19T00:00:00,"[ALTERAÇÃO, CÓDIGO BRASILEIRO DE AERONÁUTICA, ...","[{'nome': 'João Ribeiro', 'tipo': 'SENADOR', '...",ARQUIVADA AO FINAL DA LEGISLATURA,False,SF,SF,False,None,PLS,Projeto de Lei do Senado
19112,671233,https://legis.senado.leg.br/dadosabertos/proce...,2003,PLS 534/2003,534,Convalida a Resolução nº 7 do Senado Federal q...,2003-12-19T00:00:00,"[PROPOSTA, CONVALIDAÇÃO, RESOLUÇÃO, SENADO, UN...","[{'nome': 'Comissão Diretora', 'tipo': 'COMISS...",TRANSFORMADA EM NORMA JURÍDICA,False,SF,SF,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PLS,Projeto de Lei do Senado

In [12]:
props_cd.head()

,id,uri,ano,nome,numero,ementa,data_apresentacao,palavras_chave,autoria,situacao_atual,em_tramitacao,casa_atual,casa_origem,transformado_em_norma,norma_gerada,sigla_tipo,tipo
0,13756,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PDC 388/2000,388,Convoca plebiscito para o eleitorado dos estad...,2000-01-13 00:00:00,"[CONVOCAÇÃO, PLEBISCITO, OPINIÃO PUBLICA, PRIV...","[{'nome': 'Sérgio Novais', 'tipo': 'Deputado(a...",Arquivada,False,CD,CD,False,None,PDC,Projeto de Decreto Legislativo
1,13757,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PDC 389/2000,389,Aprova o texto do Acordo Multilateral de Segur...,2000-01-12 00:00:00,"[APROVAÇÃO, TEXTO, ATO INTERNACIONAL, ACORDO I...",[{'nome': 'Comissão de Relações Exteriores e d...,Transformado em Norma Jurídica,False,CD,CD,True,"{'nome': 'Decreto Legislativo nº 451/2001', 'a...",PDC,Projeto de Decreto Legislativo
2,13758,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PDC 391/2000,391,Aprova o texto do Quinto Protocolo ao Acordo G...,2000-01-12 00:00:00,"[APROVAÇÃO, TEXTO, ATO INTERNACIONAL, PROTOCOL...",[{'nome': 'Comissão de Relações Exteriores e d...,Transformado em Norma Jurídica,False,CD,CD,True,"{'nome': None, 'ano': None, 'ementa': None, 'd...",PDC,Projeto de Decreto Legislativo
3,13759,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PDC 392/2000,392,Aprova o texto do Acordo de Cooperação Cultura...,2000-01-12 00:00:00,"[APROVAÇÃO, TEXTO, ATO INTERNACIONAL, ACORDO I...",[{'nome': 'Comissão de Relações Exteriores e d...,Transformado em Norma Jurídica,False,CD,CD,True,"{'nome': 'Decreto Legislativo nº 178/2001', 'a...",PDC,Projeto de Decreto Legislativo
4,13760,https://dadosabertos.camara.leg.br/api/v2/prop...,2000,PDC 393/2000,393,Aprova a Programação Monetária relativa ao pri...,2000-01-18 00:00:00,"[APROVAÇÃO, PROGRAMAÇÃO FINANCEIRA, RESERVA MO...",[{'nome': 'Senado Federal - Comissão de Assunt...,Arquivada,False,CD,CD,False,None,PDC,Projeto de Decreto Legislativo

In [22]:
len(set(props_sf.nome).intersection(set(props_cd.nome)))

5814

In [16]:
len(props_sf[props_sf.norma_gerada.isna()])

22048

In [8]:
props_sf[(~props_sf.normaGerada.isna()) & (props_sf.tipoDocumento == "Projeto de Lei Ordinária")].head()

,autoria,casaIdentificadora,codigoMateria,dataApresentacao,dataDeliberacao,ementa,enteIdentificador,id,identificacao,siglaTipoDeliberacao,tipoConteudo,tipoDocumento,tramitando,normaGerada,dataUltimaAtualizacao,ultimaInformacaoAtualizada,apelido,urlDocumento,objetivo
16919,Câmara dos Deputados,SF,43122,2000-01-20,2000-06-20,Dispõe sobre a criação da Agência Nacional de ...,SF,3005433,PLC 3/2000,APROVADA_NO_PLENARIO,Norma Geral,Projeto de Lei Ordinária,Não,Lei nº 9.984 de 17/07/2000,NaN,NaN,NaN,NaN,Revisora
16920,Senadora Luzia Toledo (PSDB/ES),SF,43117,2000-01-20,2000-12-07,"Dá nova redação ao art. 1º da Lei nº 9608, de ...",SF,3005467,PLS 12/2000,APROVADA_EM_COMISSAO_TERMINATIVA,Norma Geral,Projeto de Lei Ordinária,Não,Lei nº 13.297 de 16/06/2016,NaN,NaN,NaN,NaN,Iniciadora
16957,Senador Tião Viana (PT/AC),SF,43472,2000-03-13,2000-06-20,"Inscreve o nome de Plácido de Castro no ""Livro...",SF,696356,PLS 56/2000,APROVADA_EM_COMISSAO_TERMINATIVA,Norma Geral,Projeto de Lei Ordinária,Não,Lei nº 10.440 de 02/05/2002,NaN,NaN,NaN,NaN,Iniciadora
16961,Câmara dos Deputados,SF,43509,2000-03-16,2000-04-25,Dispõe sobre o sistema de armazenagem dos prod...,SF,3005315,PLC 5/2000,APROVADA_NO_PLENARIO,Norma Geral,Projeto de Lei Ordinária,Não,Lei nº 9.973 de 29/05/2000,NaN,NaN,NaN,NaN,Revisora
16974,Senador Romeu Tuma (PFL/SP),SF,43531,2000-03-22,2002-04-24,"Altera a Lei nº 7713, de 22 de dezembro de 198...",SF,3005290,PLS 71/2000,APROVADA_EM_COMISSAO_TERMINATIVA,Norma Geral,Projeto de Lei Ordinária,Não,Lei nº 11.052 de 29/12/2004,NaN,NaN,NaN,NaN,Iniciadora